---
- hosts: pingnet
  remote_user: docker
  tasks:
  - name: Run and wait for up to 15 sec, poll every 5 sec
    command: pingnet
    async: 15
    poll: 3
    register: result
    ignore_errors: True 
  - debug: msg="{{ result.stdout }} "
    when: result.stdout is defined