---
# ansible-playbook -i hosts.1.yml -l netlab netlab.yml
- hosts: all
  # gather_facts: no
  become: true

  tasks:
    - name: ensure latest sysstat is installed
      apt:
        name: sysstat
        state: latest