- name: Install package appropriate to the distribution Type (Debian/Ubuntu)
  command: "{{ cmd }}"
  register: result
  ignore_errors: True
  when: ansible_os_family == "Debian" 
- debug: msg="{{ result.stdout }}"
  when: result.stdout is defined

- name: Install package appropriate to the distribution Type (RedHat/CentOS)
  command: "{{ cmd }}"
  register: result
  ignore_errors: True
  when: ansible_os_family == "RedHat"
- debug: msg="{{ result.stdout }}"  
  when: result.stdout is defined
