- hosts: WAL
  tasks:  
    - name: test next hop for 10.34.0.0
      ios_command:
        commands: 
          - sh ip route 10.34.0.0
        wait_for: result[0] contains "*via 10.71.0.1" 
    - name: test next hop for 10.110.111.0
      ios_command:
        commands: 
          - sh ip route 10.110.111.0
        wait_for: result[0] contains "*via 10.71.0.6"     