- hosts: core-DC1
  tasks:  
    - name: show interfaces on core connected to firewall
      #ios_interface:
      ios_command:
        #show int stat | i PFWP 
        commands: 'show int stat | i PFWP'
      register: FWinterfaces
    - name: log results to file
      lineinfile:
        line: "{{inventory_hostname}} === {{ FWinterfaces.stdout_lines }}"
        insertafter: EOF
        dest: "{{output}}"
      delegate_to: localhost  
    - debug: var=FWinterfaces.stdout_lines          

- hosts: dmz-DC1
  tasks:
    - name: show interfaces on dmz connected to firewall
      #ios_interface:
      ios_command:
        #show int stat | i PFWP
        commands: 'show int stat | i PFWP'
      register: FWinterfaces
    - name: log results to file
      lineinfile:
        line: "{{inventory_hostname}} === {{ FWinterfaces.stdout_lines }}"
        insertafter: EOF
        dest: "{{output}}"
      delegate_to: localhost  
    - debug: var=FWinterfaces.stdout_lines

- hosts: border-DC1
  tasks:
    - name: show interfaces on int connected to firewall
      #ios_interface:
      ios_command:
        #show int stat | i PFWP 
        commands: 'show int stat | i PFWP'
      register: FWinterfaces
    - name: log results to file
      lineinfile:
        line: "{{inventory_hostname}} === {{ FWinterfaces.stdout_lines }}"
        insertafter: EOF
        dest: "{{output}}"
      delegate_to: localhost  
    - debug: var=FWinterfaces.stdout_lines



        
       

