- hosts: core-DC1
  tags:
    - test
  tasks:  
    #- name: shutdown interfaces on core in DC1 for old firewall
    - name: show interfaces connected to firewall
      #ios_interface:
      ios_command:
        #show int stat | i FW 
        commands: 'show int stat | i FW'
    - name: open interfaces on core in DC1 for new firewall
      ios_config:
      #ios_interface:?  
        lines:
          # PFW5250P ethernet21-22 to core
          - description test core Ansible
        parents: "{{ item }}"
      with_items:
        - interface Eth1/52
        - interface Eth2/52        

- hosts: dmz-DC1
  tasks:
    - name: open interfaces in dmz of DC1 for new firewall
      ios_config:
        lines:
          # PFW5250P ethernet23-24 to core
          - description test dmz Ansible
        parents: "{{ item }}"
      with_items:
        - interface Eth1/53
        - interface Eth1/54

- hosts: border-DC1
  tasks:
    - name: open interfaces on border switch in DC1 for new firewall
      ios_config:
        lines:
          # PFW5250P ethernet1-4 to int
          - description test border Ansible
        parents: "{{ item }}"
      with_items:
        - interface Eth1/37
        - interface Eth1/38
        - interface Eth1/39
        - interface Eth1/40



        
       

