- hosts: "{{ groups['pingfull'] | shuffle }}" #groups['pingfull'][0:100]
  gather_facts: no
  max_fail_percentage: 40
  serial: 5
  tasks:
    - name: task against the sample of inventory
      raw: "{{ cmd }}"
      register: result
      #ignore_errors: True 
    - debug: msg="{{ result.stdout }}"
      when: result.stdout is defined