- hosts: localhost
  tasks:
  - add_host:      
      name: "{{ item }}"
      groups: random_host
    #with_random_choice: "{{ groups['pingfull'] }}"
    with_items: "{{ groups['pingfull'] | random }}"
    tags:
      - local
- hosts: random_host
  gather_facts: no  
  tasks:
    #- debug: var=inventory_hostname
    - name: task against random_host
      raw: "{{ cmd }}"
      register: result
      #ignore_errors: True 
      tags:
      - remote 
    - debug: msg="{{ result.stdout }}"
      when: result.stdout is defined    
     