- hosts: "{{ groups['pingfull'] | shuffle }}" #groups['pingfull'][0:100]
  vars:
    output: 'output/cmd2' 
    #filename: 'template/output.j2'
  gather_facts: no
  max_fail_percentage: 40
  serial: 5
  tasks:
    - name: task against the sample of inventory
      raw: "{{ cmd }}"
      register: result
      #ignore_errors: True 
    - debug: msg="{{ result.stdout }}" # | regex_search('ipv4-address:\\s+(\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3})')
      when: result.stdout is defined
    - name: log results to file
      lineinfile:
        line: "{{inventory_hostname}} === {{ result.stdout }}"
        insertafter: EOF
        dest: "{{output}}"
      delegate_to: localhost