- hosts: "{{ groups['pingfull'] | shuffle }}"
  gather_facts: no
  serial: 3
  tasks:
    - name: task against the limited selection group
      raw: "{{ cmd }}"
      register: result
      #ignore_errors: True 
    - debug: msg="{{ result.stdout }}"
      when: result.stdout is defined