- hosts: all
  gather_facts: no
  tasks:
    - group_by: key=limited_selection
      when: play_hosts.index(inventory_hostname) < 3 | int

- hosts: limited_selection
  gather_facts: no
  tasks:
    - debug: msg="I'm in the limited selection group!"
  tasks:
    - name: task against the limited selection group
      raw: "{{ cmd }}"
      register: result
      #ignore_errors: True 
    - debug: msg="{{ result.stdout }}"
      when: result.stdout is defined