- hosts: pingnet
  vars:
    jobids: [] 
    # file with list of targets to ping
    targets: pinglist.txt # pinglist-all.txt pinglist.txt
    threads: 200
    # prefix for results from both DCs (theping.py results pulled from DCs)
    output: ping-result
    # inventory with unique addresses (thediff.py results pushed to both DCs)
    bothDC: pingfull.yml
  tasks:
    - name: Copying files to DC1 and DC2
      copy:
        src: "{{ item }}"        
        dest: ./
        owner: docker
        group: docker
        mode: u+r
      with_items:
          - theping.py
          - pinglist-all.txt
          - pinglist.txt
      tags: 
        - local      
    - name: Ping from DC1
      command: python theping.py -t {{threads}} -f {{targets}} -o {{output}}
      when: ansible_hostname == 'dc01ap-p001mon'
      async: 30
      poll: 0
      register: result1
      ignore_errors: True 
    - name: Ping from DC2
      command: python theping.py -t {{threads}} -f {{targets}} -o {{output}}
      when: ansible_hostname == 'dc02ap-p001mon'
      async: 30
      poll: 0
      register: result2
      ignore_errors: True 
    - name: Capture Job IDs
      set_fact:
        jobids: >
                {% if item.ansible_job_id is defined -%}
                  {{ jobids + [item.ansible_job_id] }}
                {% else -%}
                  {{ jobids }}
                {% endif %}
      with_items: "{{ [ result1, result2 ] }}"
    - name: 'Wait for Job IDs'
      async_status:
         jid: "{{ item }}"
      with_items: "{{ jobids }}"
      register: jobs_result
      until: jobs_result.finished
      retries: 50
    - debug: msg="{{ jobs_result.results[0].stdout }}" # or stdout_lines
      # when: jobs_result.results[0].stdout is defined
    - name: Fetching files from DC1 and DC2  
      fetch: 
        src: ./{{output}}.yml 
        dest: ./fetched/{{output + "-" + ansible_hostname }}.yml
        flat: yes
      tags: 
        - local  
    # ansible-playbook pinger/copy_and_ping.yml --tags local  
    # docker@R90HE73F:/mnt/c/Users/irekromaniuk/Ansible$ 
    # python pinger/thediff.py -f pinger/pingfull.yml -dc1 pinger/fetched/ping-result-dc01ap-p001mon.yml -dc2 pinger/fetched/ping-result-dc02ap-p001mon.yml  
    - name: Find diff
      local_action: command python thediff.py -f {{bothDC}} -dc1 fetched/ping-result-dc01ap-p001mon.yml -dc2 fetched/ping-result-dc02ap-p001mon.yml
      tags: 
        - local
    - name: Copying pingfull.yml back  to DC1 and DC2
      copy:
        src: "{{bothDC}}"       
        dest: ./
        owner: docker
        group: docker
        mode: u+r 
      tags: 
        - local   

