- hosts: pingnet
  tasks:
    - name: example copying file with owner and permissions
      copy:
        src: theping.py
        dest: ./
        owner: docker
        group: docker
        mode: u+r
    - name: Run and wait for up to 15 sec, poll every 3 sec
      command: python theping.py
      async: 10
      poll: 3
      register: result
      ignore_errors: True 
    - debug: msg="{{ result.stdout }} "
      when: result.stdout is defined