- hosts: pingnet
  vars:
    jobids: [] 
    targets: pinglist.txt # pinglist-all.txt pinglist.txt
    threads: 200
    output: ping-result.yml
  tasks:
    - name: Copying theping.py to DC1 and DC2
      copy:
        src: "{{ item }}"        
        dest: ./
        owner: docker
        group: docker
        mode: u+r
      with_items:
          - theping.py
          - pinglist-all.txt
          - pinglist.txt  
    - name: Ping from DC1
      command: python theping.py -t {{threads}} -f {{targets}} -o {{output}}
      when: ansible_hostname == 'dc01ap-p001mon'
      async: 30
      poll: 0
      register: result1
      ignore_errors: True 
    - name: Ping from DC2
      command: python theping.py -t {{threads}} -f {{targets}} -o {{output}}
      when: ansible_hostname == 'dc02ap-p001mon'
      async: 30
      poll: 0
      register: result2
      ignore_errors: True 
    - name: Capture Job IDs
      set_fact:
        jobids: >
                {% if item.ansible_job_id is defined -%}
                  {{ jobids + [item.ansible_job_id] }}
                {% else -%}
                  {{ jobids }}
                {% endif %}
      with_items: "{{ [ result1, result2 ] }}"
    - name: 'Wait for Job IDs'
      async_status:
         jid: "{{ item }}"
      with_items: "{{ jobids }}"
      register: jobs_result
      until: jobs_result.finished
      retries: 50
    - debug: msg="{{ jobs_result.results[0].stdout }}" # or stdout_lines
      # when: jobs_result.stdout is defined
    - fetch: 
        src: ./{{output}}  
        dest: ./fetched
