---
- hosts: pingnet
  remote_user: docker
  tasks:
  - name: Run and wait for up to 15 sec, poll every 3 sec
    command: python theping.py | wc -l
    async: 10
    poll: 3
    register: result
    ignore_errors: True 
  - debug: msg="{{ result.stdout }} "
    when: result.stdout is defined